# Site settings
author: Austin Redmond
title: Marrix's Bag
header-img: img/home-bg.png
email: aredmond85@gmail.com
copyright_name: Austin Redmond
description: > # this means to ignore newlines until "baseurl:"
  Gotta Code 'Em All!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aredmond85

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
